# Generated by Django 6.1 on 2026-08-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='learning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True),
        ),
    ]
